#!/usr/bin/env python3
# This file is part of OpenBGI (https://openbgi.net).
# SPDX-License-Identifier: GPL-2.0-only
"""
gen.py - syntax-check src/os/win32/*.c against the stub Win32 headers.

Runs GCC with -fsyntax-only on every Win32 back-end file using
tools/win32stub/ in place of the SDK.  Identifiers GCC reports as
undeclared are collected into autogen.h as #defines with distinct dummy
values (so that switch cases stay distinct) and the check is repeated
until GCC reports nothing new.  API functions stay implicitly declared.

Usage: python3 tools/win32stub/gen.py   (from the project root)
Exit status 0 when every file passes with only implicit-declaration
warnings, 1 when a real error remains.
"""
import glob
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
STUB = os.path.join(ROOT, "tools", "win32stub")
AUTOGEN = os.path.join(STUB, "autogen.h")
# the back end, and the entry point's Windows half
FILES = sorted(glob.glob(os.path.join(ROOT, "src", "os", "win32", "*.c"))) + [os.path.join(ROOT, "src", "sys", "main.c")]
# -fshort-wchar: L"" literals in 16-bit units, as on Windows; a string of the
# wrong width (or any other mismatched pointer) given to one of the
# functions the stub declares is an error, as it is with the SDK
CMD = ["gcc", "-std=c99", "-fsyntax-only", "-Wall", "-Wextra", "-Wno-unused-parameter",
       "-Wno-implicit-function-declaration", "-Wno-int-conversion", "-Wno-int-to-pointer-cast",
       "-Wno-pointer-to-int-cast", "-Werror=incompatible-pointer-types", "-Wno-missing-braces",
       "-fshort-wchar", "-DBGI_WIN32", "-I" + os.path.join(ROOT, "inc"), "-I" + STUB]

UNDECL = re.compile(r"error: [‘']([A-Za-z_][A-Za-z0-9_]*)[’'] undeclared")
UNKNOWN_TYPE = re.compile(r"error: unknown type name [‘']([A-Za-z_][A-Za-z0-9_]*)[’']")


def load():
    names = {}
    if os.path.exists(AUTOGEN):
        for line in open(AUTOGEN):
            m = re.match(r"#define (\w+) (\d+)", line)
            if m:
                names[m.group(1)] = int(m.group(2))
    return names


def save(names):
    with open(AUTOGEN, "w") as f:
        f.write("/*\n * This file is part of OpenBGI (https://openbgi.net).\n"
                " * SPDX-License-Identifier: GPL-2.0-only\n *\n"
                " * autogen.h - generated by gen.py: constants the back end uses, with dummy values\n */\n")
        for n, v in sorted(names.items()):
            f.write("#define %s %d\n" % (n, v))


def main():
    names = load()
    next_value = 100000 + len(names)
    for _ in range(20):
        new = 0
        for src in FILES:
            r = subprocess.run(CMD + [src], capture_output=True, text=True)
            for m in UNDECL.finditer(r.stderr):
                if m.group(1) not in names:
                    names[m.group(1)] = next_value
                    next_value += 1
                    new += 1
            for m in UNKNOWN_TYPE.finditer(r.stderr):
                print("unknown type (add to windows.h):", m.group(1))
        save(names)
        if not new:
            break
    ok = True
    for src in FILES:
        r = subprocess.run(CMD + [src], capture_output=True, text=True)
        errors = [l for l in r.stderr.splitlines() if "error:" in l]
        warnings = [l for l in r.stderr.splitlines() if "warning:" in l]
        print("%s: %d error(s), %d warning(s)" % (os.path.relpath(src, ROOT), len(errors), len(warnings)))
        for l in errors + warnings:
            print("  " + l)
        if errors:
            ok = False
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
