#!/usr/bin/env python3
# This file is part of OpenBGI (https://openbgi.net).
# SPDX-License-Identifier: GPL-2.0-only
"""Generate inc/bgi/msg.h from tools/messages.txt.

The engine works in Shift-JIS (CP932) throughout - script text, file names
and the user-visible error messages all are.  The sources are UTF-8, so the
Japanese literals are kept in messages.txt (UTF-8, one
"ID<TAB>text<TAB>English translation[<TAB>fixed]" per line, '\n' escapes
allowed) and emitted here as octal-escaped CP932 strings.

Every message comes out as three macros: MSG_X_JA (the original), MSG_X_EN
(the translation) and MSG_X, which picks one at run time by gMsgEnglish
(English unless --lang=ja / BGI_LANG=ja).  An entry marked "fixed" (the
text engine's character tables and font names, the labels of the dialogs
the scripts open for the player) has MSG_X as the plain original.  A
translation's printf conversions must match the original's; a missing
translation falls back to the original.  Run:  python3 tools/mkmsg.py
"""
import os, re, sys
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, 'tools', 'messages.txt')
dst = os.path.join(root, 'inc', 'bgi', 'msg.h')
out = ['// This file is part of OpenBGI (https://openbgi.net).',
       '// SPDX-License-Identifier: GPL-2.0-only',
       '//',
       '// Generated by tools/mkmsg.py from tools/messages.txt - do not edit.',
       '// Every literal is CP932 (Shift-JIS) with the bytes as octal escapes;',
       '// MSG_X is the English text, or the Japanese original when gMsgEnglish',
       '// is 0 ("fixed" entries are the original only).',
       '#ifndef BGI_MSG_H_', '#define BGI_MSG_H_', '',
       'extern int gMsgEnglish; // src/core/error.c: --lang / BGI_LANG, English by default',
       '#define MSG_SELECT(ja, en) (gMsgEnglish ? (en) : (ja))', '']
seen = {}
conv = re.compile(r'%[-+ #0]*\d*(?:\.\d+)?[a-zA-Z]')

def literal(text):
    raw = text.encode('cp932')
    # octal-escape everything non-ASCII (three digits always, so a following
    # digit can never be absorbed into the escape); keep ASCII readable
    lit = ''
    for b in raw:
        if 0x20 <= b < 0x7f and chr(b) not in '"\\':
            lit += chr(b)
        else:
            lit += '\\%03o' % b
    return '"%s"' % lit

for line in open(src, encoding='utf-8'):
    line = line.rstrip('\n')
    if not line or line.startswith('#'):
        continue
    fields = line.split('\t')
    ident, text = fields[0], fields[1]
    english = fields[2] if len(fields) > 2 else ''
    fixed = len(fields) > 3 and fields[3].strip() == 'fixed'
    if ident in seen:
        sys.exit('mkmsg: duplicate id %s (also: %s)' % (ident, seen[ident]))
    seen[ident] = text
    text = text.replace('\\n', '\n')
    english = english.replace('\\n', '\n')
    if not fixed and english and conv.findall(english) != conv.findall(text):
        sys.exit('mkmsg: %s: the conversions of the translation differ from the original' % ident)
    out.append('// %s' % text.replace('\n', '\\n'))
    if fixed:
        if english:
            out.append('//   (%s)' % english.replace('\n', '\\n'))
        out.append('#define %s %s' % (ident, literal(text)))
    else:
        out.append('#define %s_JA %s' % (ident, literal(text)))
        out.append('#define %s_EN %s' % (ident, literal(english) if english else ident + '_JA'))
        out.append('#define %s MSG_SELECT(%s_JA, %s_EN)' % (ident, ident, ident))
    out.append('')
out += ['#endif // BGI_MSG_H_', '']
open(dst, 'w', encoding='utf-8').write('\n'.join(out))
print('wrote', dst)
